modLoader="javafml"
loaderVersion="[36,)"
logoFile="HellasPatcher.png"
license="Restricted"

[[mods]]
modId="hellaspatcher"
version="1.0.1"
displayName="HellasPatcher"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
'''

[[dependencies.hellaspatcher]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellaspatcher]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellaspatcher]]
modId="pixelmon"
mandatory=true
versionRange="[9.1.12,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hellaspatcher]]
modId="hellascontrol"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"